# Application
spring.application.name=selfquiz-backend
server.port=8080

# Environment Variables Import
spring.config.import=optional:file:.env.properties

# SQL Server Database
spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost};instanceName=${DB_INSTANCE:SQLEXPRESS};databaseName=${DB_NAME:SelfQuiz};integratedSecurity=${DB_AUTH_INTEGRATED:false};encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# CORS
app.cors.allowed-origins=http://localhost:5173
